// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		long N = Long.parseLong("" + args[0]);
		long i =0, j=0 ; 
		
		int counter =0;

		while (counter<N){
			counter ++;
			double r = Math.random();
			if(r>0.5)
				i++;
			else if (r<=0.5)
				j++;
		}

		System.out.println("> 0.5: "+i+" times");
		System.out.println("<= 0.5: "+j+" times");
		if (j !=0){
			double ratio = (double)i/j;
			System.out.println("Ratio: "+ratio);
		}


	}
}
